[platformio]
default_envs = paperboy
; src_dir = examples/epd_60fps_probe/main
; src_dir = examples/epd_gb_frame_probe/main
; src_dir = examples/epd_gb_touch_probe/main
src_dir = examples/epd_paperboy/main

boards_dir = boards

[env:paperboy]
platform = espressif32@6.5.0
board = T5-ePaper-S3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep+
extra_scripts =  ./script/pos_extra_script.py

build_unflags =
    -Os

build_flags =
    -O3
    -DBOARD_HAS_PSRAM
    -DPSRAM_SPEED=120MHz
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=4

lib_deps =
    Wire
